# fly.toml app configuration for FastAPI + React full-stack app
app = "market-trend-agent"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "8080"

[build]
  # Use Dockerfile for multi-service build
  dockerfile = "Dockerfile"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0

[vm]
  memory = 512
